# This file contains values from Cookiecutter

default_context:
  project_name: "parea-sdk"
  project_description: "Parea python sdk"
  organization: "parea-ai"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "parea-ai"
  email: "joel@parea.ai"
  version: "0.1.0"
  line_length: "180"
  create_example_template: "none"
